/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CertChainRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "issue" | "records" | "revoke" | "verify"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CertIssued" | "CertRevoked"): EventFragment;

  encodeFunctionData(functionFragment: "issue", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "records", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "revoke", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "verify", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "issue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace CertIssuedEvent {
  export type InputTuple = [certHash: BytesLike, issuer: AddressLike];
  export type OutputTuple = [certHash: string, issuer: string];
  export interface OutputObject {
    certHash: string;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertRevokedEvent {
  export type InputTuple = [certHash: BytesLike, issuer: AddressLike];
  export type OutputTuple = [certHash: string, issuer: string];
  export interface OutputObject {
    certHash: string;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CertChainRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CertChainRegistry;
  waitForDeployment(): Promise<this>;

  interface: CertChainRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  issue: TypedContractMethod<[certHash: BytesLike], [void], "nonpayable">;

  records: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint] & {
        issuer: string;
        issuedAt: bigint;
        revokedAt: bigint;
      }
    ],
    "view"
  >;

  revoke: TypedContractMethod<[certHash: BytesLike], [void], "nonpayable">;

  verify: TypedContractMethod<
    [certHash: BytesLike],
    [
      [string, bigint, bigint] & {
        issuer: string;
        issuedAt: bigint;
        revokedAt: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "issue"
  ): TypedContractMethod<[certHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "records"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint] & {
        issuer: string;
        issuedAt: bigint;
        revokedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revoke"
  ): TypedContractMethod<[certHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [certHash: BytesLike],
    [
      [string, bigint, bigint] & {
        issuer: string;
        issuedAt: bigint;
        revokedAt: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "CertIssued"
  ): TypedContractEvent<
    CertIssuedEvent.InputTuple,
    CertIssuedEvent.OutputTuple,
    CertIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CertRevoked"
  ): TypedContractEvent<
    CertRevokedEvent.InputTuple,
    CertRevokedEvent.OutputTuple,
    CertRevokedEvent.OutputObject
  >;

  filters: {
    "CertIssued(bytes32,address)": TypedContractEvent<
      CertIssuedEvent.InputTuple,
      CertIssuedEvent.OutputTuple,
      CertIssuedEvent.OutputObject
    >;
    CertIssued: TypedContractEvent<
      CertIssuedEvent.InputTuple,
      CertIssuedEvent.OutputTuple,
      CertIssuedEvent.OutputObject
    >;

    "CertRevoked(bytes32,address)": TypedContractEvent<
      CertRevokedEvent.InputTuple,
      CertRevokedEvent.OutputTuple,
      CertRevokedEvent.OutputObject
    >;
    CertRevoked: TypedContractEvent<
      CertRevokedEvent.InputTuple,
      CertRevokedEvent.OutputTuple,
      CertRevokedEvent.OutputObject
    >;
  };
}
